<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MyI18n\Detector\AbstractDetector'        => __DIR__ . '/src/MyI18n/Detector/AbstractDetector.php',
  'MyI18n\Detector\DetectorInterface'       => __DIR__ . '/src/MyI18n/Detector/DetectorInterface.php',
  'MyI18n\Detector\Headers'                 => __DIR__ . '/src/MyI18n/Detector/Headers.php',
  'MyI18n\Detector\PersistCapableInterface' => __DIR__ . '/src/MyI18n/Detector/PersistCapableInterface.php',
  'MyI18n\Detector\Query'                   => __DIR__ . '/src/MyI18n/Detector/Query.php',
  'MyI18n\Detector\Route'                   => __DIR__ . '/src/MyI18n/Detector/Route.php',
  'MyI18n\Detector\Session'                 => __DIR__ . '/src/MyI18n/Detector/Session.php',
  'MyI18n\LocaleStrategy'                   => __DIR__ . '/src/MyI18n/LocaleStrategy.php',
  'MyI18n\Module'                           => __DIR__ . '/src/MyI18n/Module.php',
  'MyI18n\NavigationFactory'                => __DIR__ . '/src/MyI18n/NavigationFactory.php',
);
