<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MyI18n\Detector\AbstractDetector'                 => __DIR__ . '/src/MyI18n/Detector/AbstractDetector.php',
  'MyI18n\Detector\DetectorInterface'                => __DIR__ . '/src/MyI18n/Detector/DetectorInterface.php',
  'MyI18n\Detector\Headers'                          => __DIR__ . '/src/MyI18n/Detector/Headers.php',
  'MyI18n\Detector\PersistCapableInterface'          => __DIR__ . '/src/MyI18n/Detector/PersistCapableInterface.php',
  'MyI18n\Detector\Query'                            => __DIR__ . '/src/MyI18n/Detector/Query.php',
  'MyI18n\Detector\Route'                            => __DIR__ . '/src/MyI18n/Detector/Route.php',
  'MyI18n\Detector\Session'                          => __DIR__ . '/src/MyI18n/Detector/Session.php',
  'MyI18n\Entity\Locale'                             => __DIR__ . '/src/MyI18n/Entity/Locale.php',
  'MyI18n\Entity\Translation'                        => __DIR__ . '/src/MyI18n/Entity/Translation.php',
  'MyI18n\LocaleStrategy'                            => __DIR__ . '/src/MyI18n/LocaleStrategy.php',
  'MyI18n\Module'                                    => __DIR__ . '/src/MyI18n/Module.php',
  'MyI18n\NavigationFactory'                         => __DIR__ . '/src/MyI18n/NavigationFactory.php',
  'MyI18n\Service\Factory\TranslationServiceFactory' => __DIR__ . '/src/MyI18n/Service/Factory/TranslationServiceFactory.php',
  'MyI18n\Service\Factory\TranslatorFactory'         => __DIR__ . '/src/MyI18n/Service/Factory/TranslatorFactory.php',
  'MyI18n\Service\TranslationService'                => __DIR__ . '/src/MyI18n/Service/TranslationService.php',
  'MyI18nTest\Bootstrap'                             => __DIR__ . '/tests/MyI18nTest/Bootstrap.php',
  'MyI18nTest\Service\Factory\TranslatorFactoryTest' => __DIR__ . '/tests/MyI18nTest/Service/Factory/TranslatorFactoryTest.php',
  'MyI18nTest\Service\TranslationServiceTest'        => __DIR__ . '/tests/MyI18nTest/Service/TranslationServiceTest.php',
  'MyI18nTest\TestAsset\Translations'                => __DIR__ . '/tests/MyI18nTest/TestAsset/Translations.php',
);
