<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MyI18n\Controller\LocaleController'      => __DIR__ . '/MyI18n/Controller/LocaleController.php',
  'MyI18n\Detector\AbstractDetector'        => __DIR__ . '/MyI18n/Detector/AbstractDetector.php',
  'MyI18n\Detector\DetectorInterface'       => __DIR__ . '/MyI18n/Detector/DetectorInterface.php',
  'MyI18n\Detector\Headers'                 => __DIR__ . '/MyI18n/Detector/Headers.php',
  'MyI18n\Detector\PersistCapableInterface' => __DIR__ . '/MyI18n/Detector/PersistCapableInterface.php',
  'MyI18n\Detector\Query'                   => __DIR__ . '/MyI18n/Detector/Query.php',
  'MyI18n\Detector\Route'                   => __DIR__ . '/MyI18n/Detector/Route.php',
  'MyI18n\Detector\Session'                 => __DIR__ . '/MyI18n/Detector/Session.php',
  'MyI18n\Entity\Locale'                    => __DIR__ . '/MyI18n/Entity/Locale.php',
  'MyI18n\Entity\Translation'               => __DIR__ . '/MyI18n/Entity/Translation.php',
  'MyI18n\Form\LocaleFieldset'              => __DIR__ . '/MyI18n/Form/LocaleFieldset.php',
  'MyI18n\Form\LocaleForm'                  => __DIR__ . '/MyI18n/Form/LocaleForm.php',
  'MyI18n\LocaleStrategy'                   => __DIR__ . '/MyI18n/LocaleStrategy.php',
  'MyI18n\Module'                           => __DIR__ . '/MyI18n/Module.php',
  'MyI18n\NavigationFactory'                => __DIR__ . '/MyI18n/NavigationFactory.php',
  'MyI18n\Service\LocaleService'            => __DIR__ . '/MyI18n/Service/LocaleService.php',
);
