<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 *
 * @author Stefano Torresi (http://stefanotorresi.it)
 * @license See the file LICENSE.txt for copying permission.
 * ************************************************
 */

use MyI18n\Entity\Locale;

/* @var $locales array */
$locales = $this->locales;

?>

<h3 class="section-title">
    <?= $this->translate('Languages management') ?>
</h3>

<div class="row-fluid">

    <?= $this->render('my-i18n/locale/form') ?>

    <div class="locale-list span6">

        <?php if (! empty($locales)): ?>
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th><?= $this->translate("Language") ?></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($locales as $i => $locale) :
                    /* @var $locale Locale */ ?>
                    <tr data-id="<?= $locale->getId() ?>">
                        <td class="span1"><?= $i+1 ?></td>
                        <td class="span4">
                            <?= ucfirst(\Locale::getDisplayLanguage($locale->getCode(), \Locale::getDefault())) ?>
                            <?= $locale->isDefaultLocale() ? '('.$this->translate("Default").')' : '' ?>
                        </td>
                        <td class="span2 text-right">
                            <div class="btn-group">
                            <?php if (! $locale->isDefaultLocale()) : ?>
                                <div class="btn-group">
                                    <a class="btn btn-small btn-info btn-make-default"
                                       href="<?= $this->url('admin/i18n/locales/make-default', ['code' => $locale->getCode()])?>"
                                       title="<?= $this->translate("Disable") ?>">
                                        <i class="icon-check icon-white"></i> <?= $this->translate("Make default") ?>
                                    </a>
                            <?php endif; ?>
                                <a class="btn btn-small btn-danger btn-disable"
                                   href="<?= $this->url('admin/i18n/locales/disable', ['code' => $locale->getCode()])?>"
                                   title="<?= $this->translate("Disable") ?>"><i class="icon-remove icon-white"></i> <?= $this->translate("Disable") ?></a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <p><?= $this->translate("There are no languages enabled at the moment") ?></p>
        <?php endif; ?>
    </div>

</div>
