<?php
use MyI18n\Controller\LocaleController;
use MyI18n\Entity\Locale;

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 *
 * @author Stefano Torresi (http://stefanotorresi.it)
 * @license See the file LICENSE.txt for copying permission.
 * ************************************************
 */

/** @var \MyI18n\Form\LocaleForm $form */
$form = $this->localeForm;

/* @var $locales array */
$locales = $this->locales;

$form->setAttribute('class', 'span6 form-inline');

?>
<h3 class="section-title">
    <?= $this->translate('Languages management') ?>
</h3>

<div class="row-fluid">

    <?= $this->form()->openTag($form); ?>

        <?= $this->formLabel($form->get('code')); ?><br />
        <?= $this->formSelect($form->get('code')); ?>

        <?= $this->formButton()->openTag($form->get('submit')->setAttribute('class', 'btn btn-small btn-primary margin-left-10')) ?>
            <i class="icon-check icon-white"></i>
            <?= $this->escapeHtml($this->translate($form->get('submit')->getLabel())) ?>
        <?= $this->formButton()->closeTag() ?>

        <?= $this->formRow($form->get('mode')); ?>

    <?= $this->form()->closeTag() ?>

    <div class="locale-list span6">

        <?php if (! empty($locales)): ?>
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th><?= $this->translate("Language") ?></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($locales as $i => $locale) :
                    /* @var $locale Locale */ ?>
                    <tr data-id="<?=$locale->getId()?>">
                        <td class="span1"><?= $i+1 ?></td>
                        <td class="span4"><?= ucfirst(\Locale::getDisplayLanguage($locale->getCode(), \Locale::getDefault())) ?></td>
                        <td class="span2 text-right">
                            <div class="btn-group">
                                <a class="btn btn-small btn-danger btn-disable"
                                   href="<?= $this->url('admin/i18n/locales/process', ['mode' => LocaleController::MODE_DISABLE, 'code' => $locale->getCode()])?>"
                                   title="<?= $this->translate("Disable") ?>"><i class="icon-remove icon-white"></i> <?= $this->translate("Disable") ?></a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <p><?= $this->translate("There are no languages enabled at the moment") ?></p>
        <?php endif; ?>
    </div>

</div>
