<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 *
 * @author Stefano Torresi (http://stefanotorresi.it)
 * @license See the file LICENSE.txt for copying permission.
 * ************************************************
 */

$form = $this->translationForm;
$form->prepare();
$translationFieldset = $form->get('translation');
$localeFieldset = $translationFieldset->get('locale');

$bootstrappify = function (\Zend\Form\FieldsetInterface $fieldset) use (&$bootstrappify, $form) {
    foreach ($fieldset as $element) { /** @var \Zend\Form\Element $element  */
        if ($element instanceof \Zend\Form\Element\Hidden) {
            continue;
        }
        if ($element instanceof \Zend\Form\Fieldset) {
            $bootstrappify($element);
        }
        $element->setLabelAttributes(array('class' => 'control-label'));
        $element->setAttribute('id', $form->getName().'-'.$element->getName());
        $element->setAttribute('class', 'input-block-level');
    }
};

$bootstrappify($form);

$this->formElementErrors()->setAttributes(array('class' => 'form-errors'));

$CKEditorOptions = [
    'script_options' => [
        'toolbar' => [
            ['Bold','Italic','Underline','StrikeThrough','-','Undo','Redo','-','Cut','Copy','Paste','Find','Replace','-','Outdent','Indent','-','Print'],
            ['Styles','Format','Font','FontSize'],
            '/',
            ['NumberedList','BulletedList','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
            ['Image','Table','-','Link','Smiley','TextColor','BGColor','Source']
        ],
    ],
];

?>

<h3 class="section-title"><?= $this->translate( ($form->isUpdating()?'Edit':'New') . ' translation' ) ?></h3>

<?= $this->form()->openTag($form); ?>
<div class="row-fluid">
    <div class="control-group span5">
        <?= $this->formLabel($translationFieldset->get('msgid')); ?>
        <div class="controls">
            <?= $this->CKEditor($translationFieldset->get('msgid'), $CKEditorOptions); ?>
            <?= $this->formElementErrors($translationFieldset->get('msgid')); ?>
        </div>
    </div>
    <div class="control-group span5">
        <?= $this->formLabel($translationFieldset->get('msgstr')); ?>
        <div class="controls">
            <?= $this->CKEditor($translationFieldset->get('msgstr'), $CKEditorOptions); ?>
            <?= $this->formElementErrors($translationFieldset->get('msgstr')); ?>
        </div>
    </div>
    <div class="control-group span2">
        <?= $this->formLabel($translationFieldset->get('domain')); ?>
        <div class="controls">
            <?= $this->formText($translationFieldset->get('domain')); ?>
            <?= $this->formElementErrors($translationFieldset->get('domain')); ?>
        </div>

        <?= $this->formLabel($localeFieldset->get('id')); ?>
        <div class="controls">
            <?= $this->formSelect($localeFieldset->get('id')); ?>
            <?= $this->formElementErrors($localeFieldset->get('id')); ?>
        </div>

        <div class="controls text-center margin-top-20">
            <?= $this->formButton()->openTag($form->get('submit')->setAttribute('class',
                'btn btn-primary btn-large btn-aggiungi')) ?>
            <i class="icon-plus-sign icon-white"></i>
            <?= $this->escapeHtml($this->translate($form->get('submit')->getLabel())) ?>
            <?= $this->formButton()->closeTag() ?>
            <?= $this->formRow($form->get('translationFormCSRF')) ?>
        </div>
    </div>
</div>
<?= $this->form()->closeTag(); ?>
